package 
{
	import mx.collections.ArrayCollection;
	
	/**
	 * ...
	 * @author Hidetchi
	 */
	public class Language 
	{
		public static const ac:ArrayCollection = new ArrayCollection([
			{	//ENGLISH
				LANGUAGE: "English",
				loginname: "login name",
				password: "password",
				language: "language",
				save_login_info: "save login info",
				login: "Login",
				lobby: "Main Lobby",
				refresh: "Refresh",
				wait: "Wait for Game",
				stop: "Stop Waiting",
				challenge: "Challenge",
				options: "Options",
				search: "Search",
				mute: "Mute",
				leave: "Leave PC",
				logout: "Log Out",
				back_to_game: "Back to Game",
				status_short: "Stat",
				title: "Title",
				rank: "Rank",
				name: "Name",
				country: "Country",
				rate: "Rate",
				waiter: "Waiting Player",
				country_short: "Ctry",
				thinking_time: "Time",
				handicap: "Handicap",
				black: "Black",
				white: "White",
				rule: "Rule",
				status: "Status",
				monitor: "Mon",
				opening_short: "Opng",
				watch: "Watch Game",
				view_as: "View as:",
				chat: "Chat",
				auto_scroll: "Auto-scroll",
				resign: "Resign",
				impasse: "Impasse?",
				close_game: "Close",
				check_lobby: "Check Lobby",
				watchers: "Watchers",
				kifu: "Kifu",
				copy: "Copy to Clipboard as KIF",
				save: "Save to KIF",
				replay: "Replay",
				listen: "Listen",
				search_panel: "Search Panel",
				kifu_search: "Kifu Search",
				search: "Search",
				close_search: "Close",
				result: "Result",
				opening: "Opening",
				moves: "Moves",
				game_date: "Date",
				player_search: "Player Search",
				win: "Win",
				loss: "Loss",
				total: "Total",
				percentage_short: "%-win",
				streak_short: "Streak",
				signed_up: "Signed up",
				last_updated: "Last updated",
				view_rankings: "View Rankings",
				streak: "Best Streak",
				percentage: "Winning Percentage",
				wins: "Wins",
				total_games: "Total Games",
				accept: "Accept",
				reject: "Reject",
				set_autoreply: "Set auto-reply message",
				will_be_back_in: "Will be back in",
				hours: "hours",
				minutes: "minutes",
				message: "message",
				cancel: "Cancel",
				sound: "Sound",
				blind_piece: "Blind Piece",
				save_settings: "Save settings to server",
				win_small: "win",
				loss_small: "loss",
				current: "Current",
				rated: "Rated",
				nonrated: "Non-rated"
			},
			{	//JAPANESE
				LANGUAGE: "日本語",
				loginname: "ログインID",
				password: "パスワード",
				language: "言語",
				save_login_info: "次回ログイン時まで保存",
				login: "ログイン",
				lobby: "メインロビー",
				refresh: "情報更新",
				wait: "対局待",
				stop: "待中止",
				challenge: "挑戦",
				options: "オプション",
				search: "検索",
				mute: "ミュート",
				leave: "離席",
				logout: "ログアウト",
				back_to_game: "対局室へ戻る",
				status_short: "状態",
				title: "タイトル",
				rank: "段級位",
				name: "ハンドルネーム",
				country: "国名",
				rate: "レート",
				waiter: "対局待プレーヤ",
				country_short: "国名",
				thinking_time: "持時間",
				handicap: "駒落ち",
				black: "先手",
				white: "後手",
				rule: "ルール",
				status: "進行",
				monitor: "観戦",
				opening_short: "戦型",
				watch: "観戦",
				view_as: "手番選択",
				chat: "チャット",
				auto_scroll: "自動スクロール",
				resign: "投了",
				impasse: "持将棋計算",
				close_game: "退室",
				check_lobby: "ロビーを確認",
				watchers: "観戦者",
				kifu: "棋譜",
				copy: "KIF形式でクリップボードにコピー",
				save: "KIFファイルに保存",
				replay: "再生",
				listen: "観戦",
				search_panel: "情報検索",
				kifu_search: "棋譜検索",
				search: "検索",
				close_search: "閉じる",
				result: "勝敗",
				opening: "戦型",
				moves: "手数",
				game_date: "対局日",
				player_search: "プレイヤー検索",
				win: "勝数",
				loss: "負数",
				total: "合計",
				percentage_short: "勝率",
				streak_short: "連勝数",
				signed_up: "登録日",
				last_updated: "更新日",
				view_rankings: "ランキング閲覧",
				streak: "最多連勝数",
				percentage: "勝率",
				wins: "勝局数",
				total_games: "総対局数",
				accept: "承諾",
				reject: "拒否",
				set_autoreply: "自動返信の設定",
				will_be_back_in: "離席予定時間",
				hours: "時間",
				minutes: "分",
				message: "メッセージ",
				cancel: "キャンセル",
				sound: "音声",
				blind_piece: "目隠し対局",
				save_settings: "サーバに設定を保存",
				win_small: "勝",
				loss_small: "敗",
				current: "現在",
				rated: "レート対局",
				nonrated: "非レート対局"
			},
			{ LANGUAGE: "Chinese(Simplified) - unavailable" },
			{	//CHINESE(T)
				LANGUAGE: "繁體中文",
				loginname: "登入名稱",
				password: "密碼",
				language: "語言",
				save_login_info: "保存登入資訊",
				login: "登入",
				lobby: "大廳",
				refresh: "更新",
				wait: "等待對局",
				stop: "停止等待",
				challenge: "挑戰",
				options: "選項",
				search: "搜索",
				mute: "靜音",
				leave: "離開",
				logout: "登出",
				back_to_game: "返回對局",
				status_short: "狀態",
				title: "稱號",
				rank: "等級",
				name: "名稱",
				country: "國籍",
				rate: "分數",
				waiter: "等待玩家",
				country_short: "國籍",
				thinking_time: "時限",
				handicap: "讓子",
				black: "先手",
				white: "後手",
				rule: "規則",
				status: "狀況",
				monitor: "觀戰",
				opening_short: "開局",
				watch: "Watch Game",
				view_as: "View as:",
				chat: "聊天",
				auto_scroll: "自動滾動",
				resign: "認輸",
				impasse: "僵局？",
				close_game: "關閉",
				check_lobby: "檢查大廳",
				watchers: "觀戰者",
				kifu: "棋譜",
				copy: "複製",
				save: "保存",
				replay: "棋譜重演",
				listen: "觀戰",
				search_panel: "搜索界面",
				kifu_search: "棋譜搜索",
				search: "搜索",
				close_search: "關閉",
				result: "勝負",
				opening: "開局",
				moves: "步數",
				game_date: "對局日期",
				player_search: "玩家搜索",
				win: "勝",
				loss: "負",
				total: "合計",
				percentage_short: "勝率",
				streak_short: "連勝數目",
				signed_up: "註冊日期",
				last_updated: "最後更新日期",
				view_rankings: "排行榜",
				streak: "最大連勝數",
				percentage: "勝率",
				wins: "勝利數",
				total_games: "對局數",
				accept: "接受",
				reject: "拒絕",
				set_autoreply: "設定自動訊息",
				will_be_back_in: "離開時間",
				hours: "小時",
				minutes: "分鐘",
				message: "信息",
				cancel: "取消",
				sound: "聲音",
				blind_piece: "盲棋",
				save_settings: "儲存設定",
				win_small: "勝",
				loss_small: "負",
				current: "現在",
				rated: "計分對局",
				nonrated: "不計分對局"	
			},
			{ LANGUAGE: "Spanish - unavailable"},
			{	//FRENCH
				LANGUAGE: "Français",
				loginname: "pseudonyme",
				password: "mot de passe ",
				language: "langue",
				save_login_info: "se souvenir de moi",
				login: "Entrer",
				lobby: "Salon",
				refresh: "Recharger",
				wait: "Créer une partie",
				stop: "Se retirer",
				challenge: "Défier",
				options: "Options",
				search: "Rechercher",
				mute: "Pas de son ?",
				leave: "Faire une pause",
				logout: "Déconnexion",
				back_to_game: "Revenir au jeu",
				status_short: "Stat",
				title: "Titre",
				rank: "Grade",
				name: "Nom",
				country: "Pays",
				rate: "Class",
				waiter: "Joueurs prêts",
				country_short: "Pays",
				thinking_time: "Cadence",
				handicap: "Handicap",
				black: "Noir",
				white: "Blanc",
				rule: "Règle",
				status: "Statut",
				monitor: "Spec",
				opening_short: "Ouv",
				watch: "Watch Game",
				view_as: "View as:",
				chat: "Chat",
				auto_scroll: "Défilement auto",
				resign: "Abandonner",
				impasse: "Jishogi?",
				close_game: "Fermer",
				check_lobby: "Salon",
				watchers: "Spectateurs",
				kifu: "Kifu",
				copy: "Copier",
				save: "Sauvegarder",
				replay: "Rejouer",
				listen: "Regarder",
				search_panel: "Options de recherche",
				kifu_search: "Recherche de kifu",
				search: "Rechercher",
				close_search: "Fermer",
				result: "Resultat",
				opening: "Ouverture",
				moves: "Coups",
				game_date: "Date",
				player_search: "Recherche de joueurs",
				win: "Gain",
				loss: "Défaite",
				total: "Total",
				percentage_short: "% gain",
				streak_short: "Série de gains",
				signed_up: "Inscription",
				last_updated: "Dernière partie",
				view_rankings: "Classements",
				streak: "Meilleure série de gains",
				percentage: "Pourcentage de gains",
				wins: "Gains",
				total_games: "Nombre de parties",
				accept: "Accepter",
				reject: "Rejeter",
				set_autoreply: "Message de réponse automatique",
				will_be_back_in: "Je reviens dans",
				hours: "heures",
				minutes: "minutes",
				message: "message",
				cancel: "Annuler",
				sound: "Audio",
				blind_piece: "A l'aveugle",
				save_settings: "Sauvegarder les paramètres",
				win_small: "gains",
				loss_small: "défaites",
				current: "Actuelle",
				rated: "Classée",
				nonrated: "Non classée"
			},
			{	//GERMAN
				LANGUAGE: "Deutsch",
				loginname: "Login Name",
				password: "Passwort",
				language: "Sprache",
				save_login_info: "Login Daten speichern",
				login: "Login",
				lobby: "Spielsaal",
				refresh: "Aktualisieren",
				wait: "Spiel erstellen",
				stop: "Spiel abbrechen",
				challenge: "Herausfordern",
				options: "Optionen",
				search: "Suche",
				mute: "Lautlos",
				leave: "PC verlassen",
				logout: "Ausloggen",
				back_to_game: "Zurück zum Spiel",
				status_short: "Stat",
				title: "Titel",
				rank: "Rang",
				name: "Name",
				country: "Nationalität",
				rate: "Rating",
				waiter: "Wartende Spieler",
				country_short: "Land",
				thinking_time: "Zeit",
				handicap: "Handicap",
				black: "Schwarz",
				white: "Weiß",
				rule: "Regel",
				status: "Status",
				monitor: "Beob.",
				opening_short: "Gegner",
				watch: "Watch Game",
				view_as: "View as:",
				chat: "Chat",
				auto_scroll: "Autoscroll",
				resign: "Aufgeben",
				impasse: "Impasse?",
				close_game: "Schließen",
				check_lobby: "zum Spielsaal",
				watchers: "Beobachter",
				kifu: "Kifu",
				copy: "Kopieren",
				save: "Speichern",
				replay: "Nachspielen",
				listen: "Zuschauen",
				search_panel: "Suche",
				kifu_search: "Kifu Suche",
				search: "Suchen",
				close_search: "Schließen",
				result: "Ergebnis",
				opening: "Eröffnung",
				moves: "Züge",
				game_date: "Datum",
				player_search: "Spieler Suche",
				win: "Sieg",
				loss: "Niederlage",
				total: "Total",
				percentage_short: "% Siege",
				streak_short: "Siegessträhne",
				signed_up: "Registriert",
				last_updated: "Letzte Partie",
				view_rankings: "Wertungszahlen ",
				streak: "Beste Gewinnsträhne",
				percentage: "Prozentu",
				wins: "Siege",
				total_games: "Partien gesamt",
				accept: "Annehmen",
				reject: "Ablehnen",
				set_autoreply: "Automatische Nachricht",
				will_be_back_in: "Bin zurück in",
				hours: "Stunden",
				minutes: "Minuten",
				message: "Nachricht",
				cancel: "Abbrechen",
				sound: "Sound",
				blind_piece: "Blindstein",
				save_settings: "Einstellungen speichern",
				win_small: "Siege",
				loss_small: "Niederlagen",
				current: "Aktuell",
				rated: "Gewertet",
				nonrated: "Ungewertet"
			},
			{	//POLISH
				LANGUAGE: "Polski",
				loginname: "Nazwa użytkownika",
				password: "Hasło",
				language: "Język",
				save_login_info: "Zapamiętaj dane",
				login: "Zaloguj",
				lobby: "Dojo",
				refresh: "Odśwież",
				wait: "Załóż grę",
				stop: "Zrezygnuj z czekania",
				challenge: "Zaproponuj grę",
				options: "Ustawienia",
				search: "Szukaj",
				mute: "Wycisz",
				leave: "Z/W",
				logout: "Wyloguj",
				back_to_game: "Powrót do gry",
				status_short: "Stat",
				title: "Tytuł",
				rank: "Stopień",
				name: "Nazwa",
				country: "Kraj",
				rate: "Ranking",
				waiter: "Oczekujący",
				country_short: "Kraj",
				thinking_time: "Czas",
				handicap: "Handikap",
				black: "Czarne",
				white: "Białe",
				rule: "Zasady",
				status: "Status",
				monitor: "Widzów",
				opening_short: "Otwarcie",
				watch: "Watch Game",
				view_as: "View as:",
				chat: "Chat",
				auto_scroll: "Przewijanie",
				resign: "Rezygnuj",
				impasse: "Impas?",
				close_game: "Zamknij",
				check_lobby: "Zobacz Dojo",
				watchers: "Widzowie",
				kifu: "Kifu",
				copy: "Kopiuj",
				save: "Zapisz",
				replay: "Odtwórz",
				listen: "Oglądaj",
				search_panel: "Wyszukiwarka",
				kifu_search: "Szukaj kifu",
				search: "Szukaj",
				close_search: "Zamknij",
				result: "Wynik",
				opening: "Otwarcie",
				moves: "Posunięć",
				game_date: "Data",
				player_search: "Szukaj gracza",
				win: "Zwycięstw",
				loss: "Porażek",
				total: "Razem",
				percentage_short: "% zwycięstw",
				streak_short: "Najlepsza seria",
				signed_up: "Data rejestracji",
				last_updated: "Ost. aktualizacja",
				view_rankings: "Rankingi",
				streak: "Najlepsza seria",
				percentage: "Procent zwycięstw",
				wins: "Zwycięstw",
				total_games: "Ilość gier",
				accept: "Zagraj",
				reject: "Odrzuć",
				set_autoreply: "Ustaw automatyczną odpowiedź",
				will_be_back_in: "Wrócę za",
				hours: "h",
				minutes: "min",
				message: "wiadomość",
				cancel: "Anuluj",
				sound: "Dźwięki",
				blind_piece: "Gra \"na ślepo\"",
				save_settings: "Zapisz ustawienia",
				win_small: "Zwycięstw",
				loss_small: "Porażek",
				current: "Aktualna",
				rated: "Rankingowa",
				nonrated: "Towarzyska"
			},
			{	//SWEDISH
				LANGUAGE: "Svenska",
				loginname: "Användarnamn",
				password: "Lösenord",
				language: "Språk",
				save_login_info: "Kom ihåg mig",
				login: "Logga in",
				lobby: "Huvudlobby",
				refresh: "Uppdatera",
				wait: "Vänta på parti",
				stop: "Upphör vänta",
				challenge: "Utmana",
				options: "Alternativ",
				search: "Sök",
				mute: "Ljudlös",
				leave: "Lämna datorn",
				logout: "Logga ut",
				back_to_game: "Åter till parti",
				status_short: "Stat.",
				title: "Titel",
				rank: "Rank",
				name: "Namn",
				country: "Land",
				rate: "Rating",
				waiter: "Väntande spelare",
				country_short: "Land",
				thinking_time: "Tid",
				handicap: "Handikapp",
				black: "Svart",
				white: "Vit",
				rule: "Regel",
				status: "Status",
				monitor: "Åsk.",
				opening_short: "Öpng",
				watch: "Watch Game",
				view_as: "View as:",
				chat: "Chat",
				auto_scroll: "Autoscroll",
				resign: "Ge upp",
				impasse: "Remi?",
				close_game: "Stäng",
				check_lobby: "Kolla lobby",
				watchers: "Åskådare",
				kifu: "Kifu",
				copy: "Kopiera",
				save: "Spara",
				replay: "Spela om",
				listen: "Lyssna",
				search_panel: "Sökpanel",
				kifu_search: "Sök kifu",
				search: "Sök",
				close_search: "Stäng",
				result: "Resultat",
				opening: "Öppning",
				moves: "Drag",
				game_date: "Datum",
				player_search: "Sök spelare",
				win: "Vinster",
				loss: "Förluster",
				total: "Total",
				percentage_short: "%-vinst",
				streak_short: "Vinstföljd",
				signed_up: "Registrerad",
				last_updated: "Senast uppdaterad",
				view_rankings: "Se ranking",
				streak: "Längsta vinstföljd",
				percentage: "Vinstprocent",
				wins: "Vinster",
				total_games: "Totalt antal partier",
				accept: "Acceptera",
				reject: "Avslå",
				set_autoreply: "Ställ in meddelande för autosvar",
				will_be_back_in: "Tillbaka om",
				hours: "timmar",
				minutes: "minuter",
				message: "meddelande",
				cancel: "Avbryt",
				sound: "Ljud",
				blind_piece: "Blindpjäser",
				save_settings: "Spara inställningar till server",
				win_small: "vinster",
				loss_small: "förluster",
				current: "Nuvarande",
				rated: "Rankat",
				nonrated: "Orankat"
			},
			{	//GREEK
				LANGUAGE: "Ελληνικά",
				loginname: "όνομα χρήστη",
				password: "κωδικός",
				language: "γλώσσα",
				save_login_info: "αποθήκευση στοιχείων εισόδου",
				login: "Είσοδος",
				lobby: "Αίθουσα αναμονής",
				refresh: "Ανανέωση",
				wait: "Αναμονή Παιχνιδιού",
				stop: "Τέλος Αναμονής",
				challenge: "Προκάλεσε!",
				options: "Επιλογές",
				search: "Αναζήτηση",
				mute: "Σίγαση",
				leave: "Φεύγω απ' το PC",
				logout: "Αποσύνδεση",
				back_to_game: "Επιστροφή στο παιχνίδι",
				status_short: "Κατάσταση",
				title: "Τίτλος",
				rank: "Βαθμός",
				name: "Όνομα",
				country: "Χώρα",
				rate: "Βαθμολογία",
				waiter: "Παίκτες σε αναμονή",
				country_short: "Χώρα",
				thinking_time: "Χρόνος",
				handicap: "Πλεο/μειονέκτημα",
				black: "Μαύρα",
				white: "Άσπρα",
				rule: "Κανόνες",
				status: "Κατάσταση",
				monitor: "Χρήστες",
				opening_short: "Στρατηγική",
				watch: "Watch Game",
				view_as: "View as:",
				chat: "Συνομιλία",
				auto_scroll: "Aυτόματη κύλιση",
				resign: "Παραίτηση",
				impasse: "Ατέλειωτο",
				close_game: "Έξοδος",
				check_lobby: "Αίθουσα αναμονής",
				watchers: "Παρατηρητές",
				kifu: "Kifu",
				copy: "Αντιγραφή",
				save: "Αποθήκευση",
				replay: "Ανασκόπηση",
				listen: "Παρακολούθηση",
				search_panel: "Πλαίσιο Αναζήτησης",
				kifu_search: "Αναζήτηση Παρτίδων",
				search: "Αναζήτηση",
				close_search: "Κλείσιμο",
				result: "Αποτελέσματα",
				opening: "Στρατηγική",
				moves: "Κινήσεις",
				game_date: "Ημερομηνία",
				player_search: "Αναζήτηση Παίκτη",
				win: "Νίκες",
				loss: "Ήττες",
				total: "Συνολικά",
				percentage_short: "Νίκες%",
				streak_short: "Σερί",
				signed_up: "Εγγραφή",
				last_updated: "Τελευταία Αλλαγή",
				view_rankings: "Προβολή Στατιστικών",
				streak: "Μεγαλύτερο Σερί",
				percentage: "Ποσοστό Νικών",
				wins: "Νίκες",
				total_games: "Συνολικά Παιχνίδια",
				accept: "Αποδοχή",
				reject: "Απόρριψη",
				set_autoreply: "Άφησε σημείωμα (αυτόματη απάντηση)",
				will_be_back_in: "Επιστρέφω σε",
				hours: "ώρες",
				minutes: "λεπτά",
				message: "σημείωμα",
				cancel: "Ακύρωση",
				sound: "Ήχος",
				blind_piece: "Τυφλό παιχνίδι",
				save_settings: "Αποθήκευση επιλογών ",
				win_small: "νίκες",
				loss_small: "ήττες",
				current: "Τρέχων",
				rated: "Βαθμολογούμενο",
				nonrated: "Φιλικό"
			},
			{	//ITALIAN
				LANGUAGE: "Italiano",
				loginname: "nome utente",
				password: "password",
				language: "lingua",
				save_login_info: "ricorda nome e password",
				login: "login",
				lobby: "Lobby principale",
				refresh: "Ricarica",
				wait: "Aspetta sfidante",
				stop: "Cessa l'attesa",
				challenge: "Sfida",
				options: "Opzioni",
				search: "Cerca",
				mute: "Muto",
				leave: "Pausa",
				logout: "Disconnetti",
				back_to_game: "Torna alla partita",
				status_short: "Stat",
				title: "Titolo",
				rank: "Grado",
				name: "Nome",
				country: "Paese",
				rate: "Classifica",
				waiter: "Giocatori in attesa",
				country_short: "Paese",
				thinking_time: "Tempi",
				handicap: "Handicap",
				black: "Nero",
				white: "Bianco",
				rule: "Regole",
				status: "Status",
				monitor: "Pubb.",
				opening_short: "Apert.",
				watch: "Watch Game",
				view_as: "View as:",
				chat: "Chat",
				auto_scroll: "Autoscroll",
				resign: "Arresa",
				impasse: "Patta?",
				close_game: "Chiudi",
				check_lobby: "Controlla Lobby",
				watchers: "Pubblico",
				kifu: "Kifu",
				copy: "Copia",
				save: "Salve",
				replay: "Replay",
				listen: "Guarda",
				search_panel: "Opzioni di ricerca",
				kifu_search: "Cerca kifu",
				search: "Cerca",
				close_search: "Chiudi",
				result: "Esito",
				opening: "Aperture",
				moves: "Mosse",
				game_date: "Data",
				player_search: "Cerca giocatore",
				win: "Vinte",
				loss: "Perse",
				total: "Totale",
				percentage_short: "% vittorie",
				streak_short: "Serie",
				signed_up: "Iscritto il",
				last_updated: "Ultimo agg.",
				view_rankings: "Classifiche",
				streak: "Serie migliore",
				percentage: "Percentuale vittorie",
				wins: "Vittorie",
				total_games: "Tot. partite",
				accept: "Accetta",
				reject: "Rifiuta",
				set_autoreply: "Risposta automatica",
				will_be_back_in: "Torno tra",
				hours: "ore",
				minutes: "minuti",
				message: "messaggio",
				cancel: "Cancella",
				sound: "Suoni",
				blind_piece: "Alla cieca",
				save_settings: "Salva impostazioni sul server",
				win_small: "vinte",
				loss_small: "perse",
				current: "Corrente",
				rated: "Valutata",
				nonrated: "Non valutata"
			},
			{	//PORTUGESE
				LANGUAGE: "Português",
				loginname: "Nome de usuário",
				password: "Senha",
				language: "Idioma",
				save_login_info: "Salvar informações",
				login: "Concectar",
				lobby: "Sala principal",
				refresh: "Atualizar",
				wait: "Esperar por um jogo",
				stop: "Encerrar espera",
				challenge: "Desafiar",
				options: "Opções",
				search: "Busca",
				mute: "Mudo",
				leave: "Pausa",
				logout: "Desconectar",
				back_to_game: "Voltar ao jogo",
				status_short: "Stat.",
				title: "Título",
				rank: "Rank",
				name: "Nome",
				country: "País",
				rate: "Nível",
				waiter: "Jogador em espera",
				country_short: "País",
				thinking_time: "Tempo",
				handicap: "Handicap",
				black: "Preto",
				white: "Branco",
				rule: "Regra",
				status: "Estado",
				monitor: "Assistir",
				opening_short: "Abert.",
				watch: "Watch Game",
				view_as: "View as:",
				chat: "Chat",
				auto_scroll: "Rolagem automática",
				resign: "Resignar",
				impasse: "Impasse?",
				close_game: "Fechar",
				check_lobby: "Olhar sala princ.",
				watchers: "Espectadores",
				kifu: "Kifu",
				copy: "Copiar",
				save: "Salvar",
				replay: "Replay",
				listen: "Ouvir",
				search_panel: "Painel de busca",
				kifu_search: "Buscar kifu",
				search: "Buscar",
				close_search: "Fechar",
				result: "Resultado",
				opening: "Abertura",
				moves: "Movimentos",
				game_date: "Data",
				player_search: "Buscar jogadores",
				win: "Vitória",
				loss: "Derrota",
				total: "Total",
				percentage_short: "Vitórias (%)",
				streak_short: "Série",
				signed_up: "Registrado",
				last_updated: "Ultima atualização",
				view_rankings: "Ver rankings",
				streak: "Melhor série",
				percentage: "Percentual de vitórias",
				wins: "Vitórias",
				total_games: "Total de jogos",
				accept: "Aceitar",
				reject: "Recusar",
				set_autoreply: "Mensagem de resposta automática",
				will_be_back_in: "Volto em",
				hours: "horas",
				minutes: "minutos",
				message: "mensagem",
				cancel: "Cancelar",
				sound: "Som",
				blind_piece: "Jogo cego",
				save_settings: "Salvar conf. no servidor",
				win_small: "vitórias",
				loss_small: "derrotas",
				current: "Autal",
				rated: "Avaliada",
				nonrated: "Não avaliada"
			},
			{	//BELORUSSIAN
				LANGUAGE: "Беларуская",
				loginname: "лагін",
				password: "пароль",
				language: "мова",
				save_login_info: "запомніць мяне",
				login: "Увайсці",
				lobby: "Гульнявая зала",
				refresh: "Абнавіць",
				wait: "Чакаць гульню",
				stop: "Адпачываць",
				challenge: "Прапанаваць гульню",
				options: "Налады",
				search: "Пошук",
				mute: "прыбраць гук",
				leave: "Адысці",
				logout: "Выйсці",
				back_to_game: "Вярнуцца да гульні",
				status_short: "Стан",
				title: "Тытул",
				rank: "Разрад",
				name: "Імя",
				country: "Краіна",
				rate: "Рэйтынг",
				waiter: "Гулец які чакае",
				country_short: "Краіна",
				thinking_time: "час",
				handicap: "Гандыкап",
				black: "Чорныя",
				white: "Белыя",
				rule: "Рэгл.",
				status: "Статут",
				monitor: "Назір.",
				opening_short: "Дэб.",
				watch: "Watch Game",
				view_as: "View as:",
				chat: "Чат",
				auto_scroll: "аўтапрагортка",
				resign: "Здацца",
				impasse: "Імпасс?",
				close_game: "Зачыніць",
				check_lobby: "Гульнявая зала",
				watchers: "Назіральнікі",
				kifu: "Запіс партыі",
				copy: "Капір.",
				save: "Захав.",
				replay: "Прагледзець",
				listen: "Слухаць",
				search_panel: "Панэль пошуку",
				kifu_search: "Пошук партыі",
				search: "Пошук",
				close_search: "Зачыніць",
				result: "Вынік",
				opening: "Дэбют",
				moves: "Хадоў",
				game_date: "Дата",
				player_search: "Пошук гульца",
				win: "Перам.",
				loss: "Параж.",
				total: "Ўсяго",
				percentage_short: "% перамог",
				streak_short: "Лепшая серыя",
				signed_up: "Дата рэг.",
				last_updated: "Апош. абнаўл.",
				view_rankings: "Рэйтынгі",
				streak: "Найлепшая серыя",
				percentage: "Адсотак перамог",
				wins: "Лік перамог",
				total_games: "Усяго гульняў",
				accept: "Гуляць",
				reject: "Адмовіцца",
				set_autoreply: "Налада аўтапаведамлення",
				will_be_back_in: "Вярнуся праз",
				hours: "гадзін(у)",
				minutes: "хвілін(у)",
				message: "паведамленне",
				cancel: "Адмена",
				sound: "Гук",
				blind_piece: "Гуляць \"усляпую\"",
				save_settings: "Захаваць налады на серверы",
				win_small: "перам.",
				loss_small: "параж.",
				current: "Бягучая серыя",
				rated: "рэйтынгавая",
				nonrated: "таварыская"
			},
			{	//RUSSIAN
				LANGUAGE: "Русский",
				loginname: "логин",
				password: "пароль",
				language: "язык",
				save_login_info: "запомнить меня",
				login: "Войти",
				lobby: "Игровой зал",
				refresh: "Обновить",
				wait: "Ожидать игру",
				stop: "Отдыхать",
				challenge: "Предложить игру",
				options: "Настройки",
				search: "Поиск",
				mute: "убрать звук",
				leave: "Отойти",
				logout: "Выйти",
				back_to_game: "Вернуться к игре",
				status_short: "Сост.",
				title: "Титул",
				rank: "Разряд",
				name: "Имя",
				country: "Страна",
				rate: "Рейтинг",
				waiter: "Ожидающий",
				country_short: "Страна",
				thinking_time: "время",
				handicap: "Гандикап",
				black: "Черные",
				white: "Белые",
				rule: "Регл.",
				status: "Статус",
				monitor: "Набл.",
				opening_short: "Деб.",
				watch: "Watch Game",
				view_as: "View as:",
				chat: "Чат",
				auto_scroll: "автопрокрутка",
				resign: "Сдаться",
				impasse: "Импасс?",
				close_game: "Закрыть",
				check_lobby: "Игровой зал",
				watchers: "Наблюдающие",
				kifu: "Запись партии",
				copy: "Копир.",
				save: "Сохр.",
				replay: "Просмотреть",
				listen: "Слушать",
				search_panel: "Панель поиска",
				kifu_search: "Поиск партии",
				search: "Поиск",
				close_search: "Закрыть",
				result: "Результат",
				opening: "Дебют",
				moves: "Ходов",
				game_date: "Дата",
				player_search: "Поиск игрока",
				win: "Поб.",
				loss: "Пораж.",
				total: "Всего",
				percentage_short: "% побед",
				streak_short: "Лучшая серия",
				signed_up: "Дата рег.",
				last_updated: "Посл. обновл.",
				view_rankings: "Рейтинги",
				streak: "Наилучшая серия",
				percentage: "Процент побед",
				wins: "Число побед",
				total_games: "Всего игр",
				accept: "Играть",
				reject: "Отказаться",
				set_autoreply: "Настройка автосообщения",
				will_be_back_in: "Вернусь через",
				hours: "час(ов)",
				minutes: "минут(у)",
				message: "сообщение",
				cancel: "Отмена",
				sound: "Звук",
				blind_piece: "Играть \"вслепую\"",
				save_settings: "Сохранить настройки на сервере",
				win_small: "поб.",
				loss_small: "пораж.",
				current: "Текущая серия",
				rated: "рейтинговая",
				nonrated: "нерейтинговая"
			}
		]);	
	}
	
}