package 
{
	import mx.collections.ArrayCollection;
	
	/**
	 * ...
	 * @author Hidetchi
	 */
	public class Language 
	{
		public static const ac:ArrayCollection = new ArrayCollection([
			{
				LANGUAGE: "English",
				loginname: "login name",
				password: "password",
				language: "language",
				save_login_info: "save login info",
				login: "Login",
				lobby: "Main Lobby",
				refresh: "Refresh",
				wait: "Wait for Game",
				stop: "Stop Waiting",
				challenge: "Challenge",
				options: "Options",
				search: "Search",
				mute: "Mute",
				leave: "Leave PC",
				logout: "Log Out",
				back_to_game: "Back to Game",
				status_short: "Stat",
				title: "Title",
				rank: "Rank",
				name: "Name",
				country: "Country",
				rate: "Rate",
				waiter: "Waiting Player",
				country_short: "Ctry",
				time_rule: "Time",
				handicap: "Handicap",
				black: "Black",
				white: "White",
				rule: "Rule",
				status: "Status",
				monitor: "Mon",
				opening_short: "Opng",
				chat: "Chat",
				auto_scroll: "Auto-scroll",
				resign: "Resign",
				impasse: "Impasse?",
				close_game: "Close",
				check_lobby: "Check Lobby",
				kifu: "Kifu",
				copy: "Copy",
				save: "Save",
				replay: "Replay",
				listen: "Listen",
				search_panel: "Search Panel",
				kifu_search: "Kifu Search",
				search: "Search",
				close_search: "Close",
				result: "Result",
				opening: "Opening",
				moves: "Moves",
				game_date: "Date",
				player_search: "Player Search",
				win: "Win",
				loss: "Loss",
				total: "Total",
				percentage_short: "%-win",
				streak_short: "Streak",
				signed_up: "Signed up",
				last_updated: "Last updated",
				view_rankings: "View Rankings",
				streak: "Best Streak",
				percentage: "Winning Percentage",
				wins: "Wins",
				total_games: "Total Games",
				accept: "Accept",
				reject: "Reject",
				will_be_back_in: "Will be back in",
				hours: "hours",
				minutes: "minutes",
				message: "message",
				cancel: "Cancel",
				sound: "Sound",
				blind_piece: "Blind Piece",
				save_settings: "Save settings to server",
				win_small: "win",
				loss_small: "loss",
				current: "Current",
				rated: "Rated",
				nonrated: "Non-rated"
			},
			{
				LANGUAGE: "日本語",
				loginname: "ログインID",
				password: "パスワード",
				language: "言語",
				save_login_info: "次回ログイン時まで保存",
				login: "ログイン",
				lobby: "メインロビー",
				refresh: "情報更新",
				wait: "対局待",
				stop: "待中止",
				challenge: "挑戦",
				options: "オプション",
				search: "検索",
				mute: "ミュート",
				leave: "離席",
				logout: "ログアウト",
				back_to_game: "対局室へ戻る",
				status_short: "状態",
				title: "タイトル",
				rank: "段級位",
				name: "ハンドルネーム",
				country: "国名",
				rate: "レート",
				waiter: "対局待プレーヤ",
				country_short: "国名",
				time_rule: "持時間",
				handicap: "駒落ち",
				black: "先手",
				white: "後手",
				rule: "ルール",
				status: "進行",
				monitor: "観戦",
				opening_short: "戦型",
				chat: "チャット",
				auto_scroll: "自動スクロール",
				resign: "投了",
				impasse: "持将棋計算",
				close_game: "退室",
				check_lobby: "ロビーを確認",
				kifu: "棋譜",
				copy: "コピー",
				save: "保存",
				replay: "再生",
				listen: "観戦",
				search_panel: "情報検索",
				kifu_search: "棋譜検索",
				search: "検索",
				close_search: "閉じる",
				result: "勝敗",
				opening: "戦型",
				moves: "手数",
				game_date: "対局日",
				player_search: "プレイヤー検索",
				win: "勝数",
				loss: "負数",
				total: "合計",
				percentage_short: "勝率",
				streak_short: "連勝数",
				signed_up: "登録日",
				last_updated: "更新日",
				view_rankings: "ランキング閲覧",
				streak: "最多連勝数",
				percentage: "勝率",
				wins: "勝局数",
				total_games: "総対局数",
				accept: "承諾",
				reject: "拒否",
				will_be_back_in: "離席予定時間",
				hours: "時間",
				minutes: "分",
				message: "メッセージ",
				cancel: "キャンセル",
				sound: "音声",
				blind_piece: "目隠し対局",
				save_settings: "サーバに設定を保存",
				win_small: "勝",
				loss_small: "敗",
				current: "現在",
				rated: "レート対局",
				nonrated: "非レート対局"
			}
		]);	
	}
	
}